---
authors:
  - "René Moser <mail@renemoser.net>"
dependencies:
  - ngine_io.cloudstack: '>=1.0.0'
description: 'Ansible Collection for Exoscale'
documentation: ''
homepage: 'https://github.com/ngine-io/ansible-collection-exoscale'
issues: 'https://github.com/ngine-io/ansible-collection-exoscale/issues'
license: GPL-3.0-or-later
name: exoscale
namespace: ngine_io
readme: README.md
repository: 'https://github.com/ngine-io/ansible-collection-exoscale'
tags:
  - cloud
  - dns
  - exoscale
  - ngine_io
version: 1.0.0
